title: "Anurag Khuntia"
description: "Technical Blog"
baseurl: "" # leave blank if hosted on GitHub Pages root
url: "https://anuragkhuntia.github.io"

theme: minimal-mistakes-jekyll

# Enable features
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-toc

# Breadcrumbs
breadcrumbs: true

# Default front matter
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      sidebar:
        nav: "main"
      toc: true
      toc_label: "Table of Contents"
      toc_sticky: true

# Author (used in meta and footer)
author:
  name: "Anurag Khuntia"
  avatar: "/assets/images/profile.jpg"
  bio: "Engineer. Blogger. Open Source Enthusiast."
  location: "India"

# Navigation
collections:
  posts:
    output: true
    permalink: /blog/:categories/:year/:month/:day/:title/

