trainee@HYDTEST:~/anurag/anuragkhuntia.github.io$ cat _config.yml 
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-toc
  - jekyll-paginate


title: "Anurag Khuntia"
description: "Personal blog on networking, Kubernetes, and systems."
url: "https://anuragkhuntia.github.io"

# Theme
remote_theme: mmistakes/minimal-mistakes

# Minimal Mistakes settings
minimal_mistakes_skin: default
locale: "en-US"
search: true

# Author
author:
  name   : "Anurag Khuntia"
  avatar : "/assets/images/profile.jpg"
  bio    : "Networking + Kubernetes enthusiast"
  location: "India"

# Sidebar
show_excerpts: true
breadcrumbs: true
toc: true
toc_sticky: true
paginate: 5

# Collections
collections:
  posts:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      toc: true
      toc_label: "On this page"
      toc_icon: "list"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

