title: "Anurag Khuntia"
description: "Personal blog on networking, Kubernetes, and systems."
url: "https://anuragkhuntia.github.io"

permalink: /:title/

# Theme
remote_theme: "mmistakes/minimal-mistakes"
google_site_verification: qua5khiRozT76kQTtF5V4LiWTsMUXD2spPiBURkfTWU

sass:
  sass_dir: assets/css
  style: compressed

# Ensure Jekyll processes SCSS in /assets/css
include:
  - assets/css/custom.css

# Minimal Mistakes settings
minimal_mistakes_skin: default
locale: "en-US"
search: true

# Social links
twitter_username: "" # if you have one
github_username: anuragkhuntia
linkedin: kanurag03

# Author
author:
  name   : "Anurag Khuntia"
  avatar : "/assets/images/profile.jpg"
  bio    : "Networking + Kubernetes enthusiast"
  location: "India"

# Sidebar
show_excerpts: true
breadcrumbs: true
toc: true
toc_sticky: true
paginate: 5

# Collections
collections:
  posts:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      toc: true
      toc_label: "On this page"
      toc_icon: "list"
      related: true
      prev_next: false
      custom_css:
        - /assets/css/custom.css

# Plugins (only define once)
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-toc
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

related_posts:
  heading: "You may also like"
  limit: 3   # number of posts to show

