# Site Settings
title: "Anurag Khuntia"
description: "Platform Engineer | DevOps | Cloud | Blog + Portfolio"
baseurl: "" # leave empty for user site
url: "https://anuragkhuntia.github.io"

# Use Minimal Mistakes as remote theme
remote_theme: "mmistakes/minimal-mistakes"

breadcrumbs: true

permalink: /:categories/:year/:month/:day/:title/

# Plugins required by GitHub Pages and theme
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Author settings
author:
  name: "Anurag Khuntia"
  avatar: "/assets/images/profile.jpg"
  bio: "Platform Engineer with 3+ years in DevOps, Kubernetes, and Cloud."
  location: "India"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/anuragkhuntia"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/kanurag03"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:anuragkhuntia03@gmail.com"

# Pagination for blog index
paginate: 5
paginate_path: "/blog/page:num/"

# Syntax highlighting with Rouge
highlighter: rouge

# Optional typography style from Minimal Mistakes
typography_style: chesterish

# Fonts — override default Minimal Mistakes fonts for professional look
font_family_sans: "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif"
font_family_serif: "Merriweather, Georgia, 'Times New Roman', Times, serif"

# Sass settings for compressed output (optional custom scss)
sass:
  style: compressed

# Custom CSS file loading
assets:
  css:
    - /assets/css/custom.scss

# In _config.yml
collections:
  posts:
    output: true

# Enable excerpts
excerpt_separator: <!--more-->

# Navigation Links
#nav:
#  - title: "Home"
#    url: /
#  - title: "Blog"
#    url: /blog/
#  - title: "About"
#    url: /about/

# Add navigation
header_pages:
  - index.html
  - _pages/about.md
  - blog.html
    #  - resume.pdf

# _config.yml
seo:
  type: "Person"
  name: "Anurag Khuntia"
  twitter: username_if_any

header:
  teaser: /assets/images/kubernets_onprem_fabric.png

