title: "Anurag Khuntia"
description: "Portfolio and Blog — DevOps | Cloud | Platform Engineering"
baseurl: "" # leave blank for user site
url: "https://anuragkhuntia.github.io"

theme: minima   # built-in theme (simple + blog support)

# Optional settings
author:
  name: "Anurag Khuntia"
  email: "anuragkhuntia03@gmail.com"
